# Generated by Django 2.2.5 on 2019-10-10 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeDislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, max_length=200, null=True)),
                ('object_id', models.PositiveIntegerField(verbose_name='ایدی قسمت')),
                ('content', models.TextField(blank=True, default='text', verbose_name='متن')),
                ('liked', models.BooleanField(default=False, verbose_name='دوست داشته')),
                ('disliked', models.BooleanField(default=False, verbose_name='دوست نداشته')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likedislike', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لایک/دیس لایک',
                'verbose_name_plural': ' لایک ها /دیس لایک ها',
                'ordering': ('-timestamp',),
            },
        ),
    ]
