# Generated by Django 2.2.5 on 2019-10-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedislike',
            name='disliked',
        ),
        migrations.RemoveField(
            model_name='likedislike',
            name='liked',
        ),
        migrations.AddField(
            model_name='likedislike',
            name='likedislike',
            field=models.CharField(blank=True, choices=[('like', 'دوست دارد'), ('dislike', 'دوست ندارد')], max_length=10, verbose_name='دوست/نه دوست'),
        ),
    ]
