# Generated by Django 2.2.6 on 2019-12-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='users_profile/img/%Y-%m-%d', verbose_name='اواتار'),
        ),
    ]
