version: '3'
services:

  db:
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=POSTGRES_DB
      - POSTGRES_USER=POSTGRES_USER
      - POSTGRES_PASSWORD=POSTGRES_PASSWORD
  rabbitmq:
    image: rabbitmq:3.7-alpine
  redis:
    restart: always
    image: redis:latest
    expose:
      - "6379"
  src:
    build:
      context: .
    volumes:
      - ./:/src
    # command: sh -c "python manage.py runserver 0.0.0.0:8000"
    command: sh -c "gunicorn advance_blog.wsgi -b 0.0.0.0:8000"
    # command: sh -c "gunicorn advance_blog.wsgi:application --bind 0.0.0.0:8000"
    # command: sh -c "python manage.py migrate && gunicorn advance_blog.wsgi -b 0.0.0.0:8000"
    # command: gunicorn app:app -b :8000 --name app --log-level=debug --log-file=-
    # command: gunicorn advance_blog.wsgi:application --bind 0.0.0.0:8000
    # env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
      - redis
      - celery
  celery:
    build: .
    command: sh -c "celery -A advance_blog worker -l info"
    ports: []
    volumes:
      - .:/src
    depends_on:
      - db
      - rabbitmq
      - redis