# Generated by Django 2.2.5 on 2019-10-10 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=120, verbose_name='عنوان دسته')),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='تصویر')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='اسلاگ')),
                ('image', models.ImageField(upload_to='', verbose_name='تصویر عنوان')),
                ('content', tinymce.models.HTMLField()),
                ('read_time', models.TimeField(blank=True, null=True, verbose_name='زمان لازم برای خواندن پست')),
                ('published', models.BooleanField(default=True, verbose_name='پست شده')),
                ('special', models.BooleanField(default=False, verbose_name='ویژه')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('category', models.ManyToManyField(related_name='post', to='posts.Category', verbose_name='دسته')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست ها',
                'ordering': ('-created',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
