# Generated by Django 2.2.6 on 2019-11-28 06:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_previous'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=90), blank=True, null=True, size=5, verbose_name='تگ ها'),
        ),
    ]
