# Generated by Django 2.2.6 on 2019-12-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20191208_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='posts/img/%Y-%m-%d', verbose_name='تصویر عنوان'),
        ),
    ]
